import type { UpgradeDef } from "./types";
import { BALANCE } from "../economy/balance";

// IDs are stable — see `04-economy-formulas.md` §4 (one-time) and §14 (repeatable).
// Each one-time category is gated linearly: owning the previous item unlocks the next.
export const UPGRADE_CATALOG: UpgradeDef[] = [
  // --- Repeatable (leveled) — viewer pillar: core clicker improvements ---
  {
    id: "engagement_boost",
    category: "repeatable",
    pillar: "viewer",
    name: "Engagement Boost",
    description: `+${BALANCE.upgrades.engagementBoost.postPowerAddPerLevel} post power per level`,
    effect: { postPowerAdd: BALANCE.upgrades.engagementBoost.postPowerAddPerLevel },
    repeatable: true,
    baseCost: { coins: BALANCE.upgrades.engagementBoost.baseCost },
    costGrowth: BALANCE.upgrades.engagementBoost.costGrowth,
    maxLevel: BALANCE.upgrades.engagementBoost.maxLevel,
  },
  {
    id: "loyal_followers",
    category: "repeatable",
    pillar: "viewer",
    name: "Loyal Followers",
    description: `+${BALANCE.upgrades.loyalFollowers.followerConversionAddPerLevel} follower conversion per level`,
    effect: { followerConversionAdd: BALANCE.upgrades.loyalFollowers.followerConversionAddPerLevel },
    repeatable: true,
    baseCost: { coins: BALANCE.upgrades.loyalFollowers.baseCost },
    costGrowth: BALANCE.upgrades.loyalFollowers.costGrowth,
    maxLevel: BALANCE.upgrades.loyalFollowers.maxLevel,
  },
  {
    id: "auto_engage_bot",
    category: "repeatable",
    pillar: "viewer",
    name: "Auto-Engage Bot",
    description: `+${BALANCE.upgrades.autoEngageBot.passiveCoinsAddPerLevel} coins/sec per level`,
    effect: { passiveCoinsAdd: BALANCE.upgrades.autoEngageBot.passiveCoinsAddPerLevel },
    repeatable: true,
    baseCost: { coins: BALANCE.upgrades.autoEngageBot.baseCost },
    costGrowth: BALANCE.upgrades.autoEngageBot.costGrowth,
    maxLevel: BALANCE.upgrades.autoEngageBot.maxLevel,
  },

  // --- Gear ---
  // viewer: pure clicker/income; no run-stat effects
  {
    id: "ring_light",
    category: "gear",
    pillar: "viewer",
    name: "Ring Light",
    description: "+3 post power",
    cost: { coins: 50 },
    effect: { postPowerAdd: 3 },
  },
  // live: has run-stat effect (troll resist)
  {
    id: "usb_mic",
    category: "gear",
    pillar: "live",
    name: "USB Mic",
    description: "+6 post power, +10% troll resistance",
    cost: { coins: 150 },
    requires: { upgrades: ["ring_light"] },
    effect: { postPowerAdd: 6, runTrollResistAdd: 0.1 },
  },
  {
    id: "tripod",
    category: "gear",
    pillar: "viewer",
    name: "Tripod",
    description: "+2 coins/sec passive income",
    cost: { coins: 300 },
    requires: { upgrades: ["usb_mic"] },
    effect: { passiveCoinsAdd: 2 },
  },
  {
    id: "phone_gimbal",
    category: "gear",
    pillar: "live",
    name: "Gimbal",
    description: "+15 post power, +10 starting LIVE viewers",
    cost: { coins: 800 },
    requires: { upgrades: ["tripod"] },
    effect: { postPowerAdd: 15, runStartViewersAdd: 10 },
  },
  {
    id: "dslr",
    category: "gear",
    pillar: "live",
    name: "DSLR Camera",
    description: "+30 post power, ×1.25 starting LIVE viewers",
    cost: { coins: 2500 },
    requires: { upgrades: ["phone_gimbal"] },
    effect: { postPowerAdd: 30, runStartViewersMult: 1.25 },
  },
  {
    id: "green_screen",
    category: "gear",
    pillar: "live",
    name: "Green Screen",
    description: "+25 coins/sec passive income, unlocks Pin Comment reaction",
    cost: { coins: 6000 },
    requires: { upgrades: ["dslr"] },
    effect: { passiveCoinsAdd: 25, unlocksReaction: "pin_comment" },
  },
  {
    id: "studio_lights",
    category: "gear",
    pillar: "live",
    name: "Studio Lights",
    description: "×1.3 all income, ×1.2 LIVE gift rate",
    cost: { coins: 18000 },
    requires: { upgrades: ["green_screen"] },
    effect: { multiplierMult: 1.3, runGiftRateMult: 1.2 },
  },
  {
    id: "creator_rig",
    category: "gear",
    pillar: "live",
    name: "Creator Rig",
    description: "+120 post power, ×1.5 starting LIVE viewers",
    cost: { coins: 60000, diamonds: 5 },
    requires: { upgrades: ["studio_lights"] },
    effect: { postPowerAdd: 120, runStartViewersMult: 1.5 },
  },

  // --- Software ---
  // live: unlocks a run reaction
  {
    id: "capcut",
    category: "software",
    pillar: "live",
    name: "Editing App",
    description: "+0.3 follower conversion, unlocks Clapback reaction",
    cost: { coins: 100 },
    effect: { followerConversionAdd: 0.3, unlocksReaction: "clapback" },
  },
  // viewer: passive income, no run stats
  {
    id: "scheduler",
    category: "software",
    pillar: "viewer",
    name: "Post Scheduler",
    description: "+6 coins/sec passive income",
    cost: { coins: 400 },
    requires: { upgrades: ["capcut"] },
    effect: { passiveCoinsAdd: 6 },
  },
  {
    id: "hashtag_tool",
    category: "software",
    pillar: "viewer",
    name: "Hashtag Tool",
    description: "×1.25 all income",
    cost: { coins: 1200 },
    requires: { upgrades: ["scheduler"] },
    effect: { multiplierMult: 1.25 },
  },
  {
    id: "analytics_pro",
    category: "software",
    pillar: "live",
    name: "Analytics Pro",
    description: "+0.6 follower conversion, ×1.15 LIVE gift rate",
    cost: { coins: 4000 },
    requires: { upgrades: ["hashtag_tool"] },
    effect: { followerConversionAdd: 0.6, runGiftRateMult: 1.15 },
  },
  {
    id: "trend_radar",
    category: "software",
    pillar: "live",
    name: "Trend Radar",
    description: "Unlocks Shoutout reaction, +40 starting LIVE viewers",
    cost: { coins: 10000 },
    requires: { upgrades: ["analytics_pro"] },
    effect: { unlocksReaction: "shoutout", runStartViewersAdd: 40 },
  },
  {
    id: "algo_hacks",
    category: "software",
    pillar: "viewer",
    name: "Algorithm Hacks",
    description: "×1.6 all income",
    cost: { coins: 35000 },
    requires: { upgrades: ["trend_radar"] },
    effect: { multiplierMult: 1.6 },
  },
  {
    id: "viral_engine",
    category: "software",
    pillar: "live",
    name: "Viral Engine",
    description: "×2 all income, unlocks Go Off reaction",
    cost: { coins: 120000, diamonds: 15 },
    requires: { upgrades: ["algo_hacks"] },
    effect: { multiplierMult: 2, unlocksReaction: "go_off" },
  },
];
